#DataBases
db_url: 'jdbc:mariadb://localhost:3306/survivalgame'
db_user: 'root'
db_password: 'root'
npc_location:
  world: 'world'
  x: -584
  y: 63
  z: 136
  pitch: -25.4
  yaw: -0
arenas:
  arena1:
    max_player_arena: 2
    common_chest:
      items:
        - 'stone'
        - 'dirt'
        - 'diamond_sword'
      location:
        '0':
          world: 'test'
          x: -522
          y: 69
          z: 16
    epic_chest:
      items:
        - 'diamond'
        - 'chest'
        - 'golden_sword'
      location:
        '0':
          world: 'test'
          x: -522
          y: 70
          z: 16
    rare_chest:
      items:
        - 'stone'
        - 'chest'
        - 'iron_sword'
      location:
        '0':
          world: 'test'
          x: -522
          y: 70
          z: 16
    legendary_chest:
      items:
        - 'snow'
        - 'arrow'
        - 'diamond_sword'
      location:
        '0':
          world: 'test'
          x: -522
          y: 71
          z: 16
    spawn_location:
      '0':
        world: 'test'
        x: -511.0
        y: 69.0
        z: 27.0
        pitch: 104.4
        yaw: 9.5
lobyArena:
  world: 'test'
  x: -526.400
  y: 82
  z: 25.29
#user MINUTES or SECONDS
timer_Type: 'seconds'
#Round tine
round_tine: 1