#DataBases
db_host: 'localhost'
db_name: 'survivalgame'
db_port: 3306
db_user: 'root'
db_password: 'root'

#SurvivalGame set_up
max_player_arena: 2
npc_location:
  world: 'test'
  x: -518
  y: 69
  z: 28.36
  pitch: -179.9
  yaw: -6
arenas: #spawn in arena
  spawn_location:
    '1':
      world: 'test'
      x: -511
      y: 69
      z: 27
      pitch: 104.4
      yaw: 9.5
    '2':
      world: 'test'
      x: -511
      y: 69
      z: 29
      pitch: 104.4
      yaw: 9.5
    '3':
      world: 'test'
      x: -511
      y: 69
      z: 29
      pitch: 104.4
      yaw: 9.5
random_amount: 13
spawnPlayer:
  '0':
    x: -522
    y: 69
    z: 17
    world: 'test'
#user MINUTES or SECONDS
timer_Type: 'seconds'

#Round tine
round_tine: 1

#Chest settings
common_chest:
  items:
    - 'stone'
    - 'cactus'
    - 'diamond_sword'
  location:
    '0':
      world: test
      x: -522
      y: 69
      z: 16