#DataBases
db_host: 'localhost'
db_name: 'survivalgame'
db_port: 3306
db_user: 'root'
db_password: 'root'

#SurvivalGame set_up
max_player_arena: 2
default_spawn:
  world: 'world'
  x: 4
  y: 4
  z: 4
  pitch: 4
  yaw: 4
random_amount: 13
spawnPlayer:
  0:
    world:
    x:
    Y:
    Z:
#user MINUTES or SECONDS
timer_Type: 'seconds'

#Round tine
round_tine: 1

#Chest settings
common_chest:
  items:
    - 'stone'
    - 'cactus'
    - 'diamond_sword:1'
  location:
    '0':
      world: test
      x: -522
      y: 70
      z: 16