name: GameSurvival
version: '1.0-SNAPSHOT'
main: ro.mihaaiiii.gamesurvival.GameSurvival
api-version: 1.17
commands:
  set:
  set_spawn:
    description: 'seteaza spawnul main in arena'
  setPspawn:
    description: 'seteaza spawnul jucatoriilor in arena'
  common_chest:
    description: 'seteaza chest'
  join:
    description: 'adauga jucatorii in arena'
  setNpc:
    description: 'Set npc join'
